#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  config:
    activate:
      on-profile: local
  application:
    name: api

  datasource:
    url: jdbc:mysql://localhost:3306/yageum
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(I+PDk31WFTOU39AypeTrZFVbb8MSpV9oL9q2C3HGQD8/1+Wj7fVmMw==)
    password: ENC(TRk22TqlQbz1iTprwMnpiEMZLFAarFDjMf/iTDTnDCw=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 600000 # 10분

jwt:
  secret: ENC(acbDZy8Gz9X1OSL3fjOHVg==)

#user-service:
#  url: http://localhost:8081/user-service