spring:
  config:
    activate:
      on-profile: prod
  application:
    name: Yageum-Service

  datasource:
    url: jdbc-secretsmanager:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 600000 # 10분

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: yg-chatting-group
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

mongodb:
  client: ${MONGO_CLIENT}
  name: ${MONGO_NAME}

jwt:
  secret: ${JWT_SECRET}