#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  config:
    activate:
      on-profile: local
  application:
    name: Yageum-Service

  datasource:
    url: ENC(6F1w8KuzvBr9UjCNifhN9Jro3FjhGurGsGWRcxdELYqPsAmGI9ujNLRgIOFqipj5q9edDaPE46/Etzo4HR5KFnsjnxX5fnioGp8Udtom3l9kN1r6VPqULg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(P4y+dlEjQ2R53xb9Z0Y1Iw==)
    password: ENC(c7T4i7tWbLs3Rp8lbHoE2FXKc/3qhz0w)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(CIvYzOOsnJk75Qgq8URIoHLVt8HtWPBSOXlzHf2OmrLJfMyiz6lUkQ==)
    password: ENC(paJhV++bBr9w8oCQduzSl3ZOry0+mGdUBvsnfnYoJ7Y=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 600000

jwt:
  secret: ENC(C2bA91/W5AnYOlwQ7s2QTEbw26I0epS+)
