spring:
  config:
    activate:
      on-profile: prod
  application:
    name: Yageum-Service

  datasource:
    url: jdbc-secretsmanager:mysql://yg-database.cjq2ocek4xmp.ap-northeast-2.rds.amazonaws.com:3306/yageum
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    username: prod/AppBeta/MysqlYG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: redis
    port: 6379

  mail:
    host: ${mail.host}
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 600000 # 10분

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # 컨슈머 서버 주소
      group-id: yg-chatting-group
    producer:
      bootstrap-servers: localhost:9092 # 프로듀서 서버 주소

mongodb:
  client: ${mongo.client}
  name: ${mongo.name}

jwt:
  secret: ${jwt.secret}

#user-service:
#  url: http://52.78.155.253:8081/user-service
