eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    activate:
      on-profile: local
  application:
    name: api

  datasource:
    url: jdbc:mysql://localhost:33061/iceAmericano
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: iceAmericano

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ENC(acbDZy8Gz9X1OSL3fjOHVg==)

user-service:
  url: http://localhost:8081/user-service