 version: '3.8'

services:
  # mysql
  mysql:
    container_name: IA_mysql
    image: mysql:8.0
    env_file:
      - .env\
    environment:
      TZ: Asia/Seoul
    ports:
      - "33061:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'